apiVersion: apps/v1
kind: Deployment
metadata:
  name: pylon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pylon-app
  template:
    metadata:
      labels:
        app: pylon-app
    spec:
      containers:
        - name: pylon-app
          image: pylon:latest
          imagePullPolicy: Never  # Use local image
          ports:
            - containerPort: 8010
          env:
            - name: POSTGRES_SERVER
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: pylon_db
---
apiVersion: v1
kind: Service
metadata:
  name: pylon-app-service
spec:
  type: LoadBalancer
  selector:
    app: pylon-app
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010
